### ISSUE TITLE
Helix GOPLS Configuration Out of Date

### ISSUE THREAD

**Issue by brycefisher** [bazel-contrib/rules_go#3905]
### What version of rules_go are you using?

N/A

### What version of gazelle are you using?

N/A

### What version of Bazel are you using?

N/A

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

MacOS M1 / armv7

### Any other potentially useful information about your toolchain?

N.A

### What did you do?

I followed the directions in the Wiki for configuring Bazel IDE in helix via GOPLS:
https://github.com/bazelbuild/rules_go/wiki/Editor-setup#helix-editor

### What did you expect to see?

The helix editor to start normally and LSP features working

### What did you see instead?

```
Failed to parse language config: unknown field `config`, expected one of `name`, `language-id`, `scope`, `file-types`, `shebangs`, `roots`, `comment-token`, `comment-tokens`, `block-comment-tokens`, `text-width`, `soft-wrap`, `auto-format`, `formatter`, `diagnostic-severity`, `grammar`, `injection-regex`, `language-servers`, `indent`, `debugger`, `auto-pairs`, `rulers`, `workspace-lsp-roots`, `persistent-diagnostic-sources`
in `language`

Press <ENTER> to continue with default language config
```

### Updated COnfig that works for me 

version - helix 24.3 (2cadec0b)

```toml
[language-server.gopls]
command = "gopls"
environment = { "GOPACKAGESDRIVER" = "./tools/bazel/gopackagesdriver.sh" }

[[language]]
name = "go"
file-types = ["go"]
language-servers = ["gopls"]
```

**Comment by theletterjeff** [comment]
Were you able to add the extra args included in the current wiki page, e.g., `gofumpt`, `staticcheck`, `usePlaceholders`, etc.? If so, you could edit the wiki page with this solution and close this issue.

**Comment by brycefisher** [comment]
I wasn't able to add the additional args but I can try to figure it out and post in this issue.

As far as I know, I don't have edit rights for the wiki.

**Comment by brycefisher** [comment]
I think perhaps the script referenced is meant to set whatever arguments are needed by gopls

**Comment by RmStorm** [comment]
I'm pretty sure you can just edit the wiki! I just edited it at least to change to Helix's new multi LSP config format. So I think this issue can be closed now?
https://github.com/bazel-contrib/rules_go/wiki/Editor-setup#helix-editor
