### ISSUE TITLE
Transfer rules_go to bazel-contrib

### ISSUE THREAD

**Issue by meteorcloudy** [bazel-contrib/rules_go#4107]
**Description:**

This issue proposes transferring the rules_go repository from the `bazelbuild` GitHub organization to the `bazel-contrib` GitHub organization, which is owned by the [Community for Bazel](https://github.com/bazel-contrib/.github/blob/master/Community%20for%20Bazel%20Technical%20Charter.pdf) project under the Linux Foundation.

**GitHub Discussion:** https://github.com/orgs/bazelbuild/discussions/2

**Impacts:**

* GitHub issues & PRs will be transferred to the new repository.
* Branch protection rules will need to be transferred to the new repository.
* Individual maintainers will be transferred to the new repository.
* GitHub teams will NOT be transferred to the new repository and will need to be re-created.
* Bazel CI configurations will need to be updated to point to the new repository.

Read more on [Transferring a repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) from GitHub documentation.

**Checklist:**

* [x] Obtain approval from the current project maintainers (@bazelbuild/go-maintainers).
* [x] Obtain approval from the bazel-contrib SIG (@alexeagle).
* [x] Initiate the transfer process on GitHub (@meteorcloudy).
* [x] Update Bazel CI settings and confirm presubmit & postsubmit work (@meteorcloudy).

**Comment by alexeagle** [comment]
Notes from SIG meeting: this transfer was unanimously approved by a thumbs-up vote.

**Comment by fmeum** [comment]
I approve for @bazelbuild/go-maintainers

**Comment by meteorcloudy** [comment]
Do we need approvals from other go maintainers? I'll first create a @bazel-contrib/go-maintainers team and invite the same members.

**Comment by meteorcloudy** [comment]
@bazel-contrib/go-maintainers is now created and I granted @fmeum maintainer role.

**Comment by lbcjbb** [comment]
Transfert this repository to another org will change the import path of the Go library `github.com/bazelbuild/rules_go/go/runfiles`.
Will this module rename in the go.mod be made at the same time?

**Comment by fmeum** [comment]
Assuming that the redirect remains in place, we should be able to make it after the transfer, before the next release.

**Comment by lbcjbb** [comment]
It's perfect. Thanks

**Comment by meteorcloudy** [comment]
Transfer is done, Bazel CI has been updated, let me know if there is any problem.
