### ISSUE TITLE
Feature: Build pure go_binary targets without cc toolchain

### ISSUE THREAD

**Issue by sallustfire** [bazel-contrib/rules_go#4145]
### What version of rules_go are you using?

v0.50.1

### What version of Bazel are you using?

7.3.2

### Does this issue reproduce with the latest releases of all the above?

Yes

### What operating system and processor architecture are you using?

PopOS 22.04

### What did you do?

go_binary targets with pure = "on" still participate in cc toolchain selection. This can be seen in one of the examples in the repo:
```
bazel cquery "somepath(//tests/core/go_binary:static_pure_bin, kind(toolchain, deps(//tests/core/go_binary:static_pure_bin)))"
INFO: Analyzed target //tests/core/go_binary:static_pure_bin (1 packages loaded, 14 targets configured).
INFO: Found 1 target...
//tests/core/go_binary:static_pure_bin (5c86453)
//:go_context_data (55832f6)
//:stdlib (c5fe2ab)
//:cgo_context_data (c5fe2ab)
@bazel_tools//tools/cpp:optional_current_cc_toolchain (c5fe2ab)
INFO: Elapsed time: 0.122s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

This happens because //:go_context_data has a dependency on //:cgo_context_data. There are two other places where this same cgo dependency enters //:stdlib and //:cgo_context_data_proxy.

### What did you expect to see?

Only the go SDK should be selected

```
bazel cquery "somepath(//tests/core/go_binary:static_pure_bin, kind(toolchain, deps(//tests/core/go_binary:static_pure_bin)))"
INFO: Analyzed target //tests/core/go_binary:static_pure_bin (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
//tests/core/go_binary:static_pure_bin (5c86453)
@go_sdk//:go_linux_amd64-impl (5c86453)
INFO: Elapsed time: 0.126s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 0 total actions
```

**Comment by aaomidi** [comment]
I _think_ based on #4154, this might still be an issue.
