### ISSUE TITLE
how do I add the `out` parameter to the `go_binary` automatically generated by gazelle?

### ISSUE THREAD

**Issue by jettcc** [bazel-contrib/rules_go#4202]
### What version of rules_go are you using?
```
bazel_dep(name = "rules_go", version = "0.51.0", repo_name = "io_bazel_rules_go")
```
### What version of gazelle are you using?

```
bazel_dep(name = "gazelle", version = "0.40.0")
```

### What version of Bazel are you using?

```
❯ bazelisk version
Bazelisk version: 1.24.1
Build label: 8.0.0
Build target: @@//src/main/java/com/google/devtools/build/lib/bazel:BazelServer
Build time: Mon Dec 09 18:02:00 2024 (1733767320)
Build timestamp: 1733767320
Build timestamp as int: 1733767320
```

### Does this issue reproduce with the latest releases of all the above?

> yes, i think this is a configuration issue. Is it possible to resolve it using methods like `# gazelle:resolve`?

### What operating system and processor architecture are you using?
```
❯ uname
Darwin(MacBook Pro)
❯ uname -m
arm64
```

### What did you expect to see?
i hope to solve the problem with a one-sentence description: i want to include the out parameter when generating go_binary using gazelle.

**Comment by jettcc** [comment]
I am a student who has just recently come into contact with the open-source community. If my way of asking questions and handling issues is incorrect, please correct me. Thank you.

**Comment by fmeum** [comment]
What do you want Gazelle to set `out` to? Do you want to use a different naming scheme for all (of many) `go_binary` targets?

**Comment by jettcc** [comment]
> What do you want Gazelle to set out to? Do you want to use a different naming scheme for all (of many) go_binary targets?

@fmeum thx for your reply, now, when I use bazel to compile golang, `build.bazel` file will be generated:
```
go_binary(
    name = "todo",
    embed = [":todo_lib"],
    visibility = ["//visibility:public"],
)
```
 but I hope to set an `out` parameter in it, for example(the `out` here is added by me manually):
 ```
go_binary(
    name = "todo",
    out = "todo",
    embed = [":todo_lib"],
    visibility = ["//visibility:public"],
)
```

in my monorepo, there are dozens of subprojects, and I don't want to manually add this parameter in every `BUILD.bazel` adjacent to `main.go`. I'm wondering if there's a way to configure `gazelle` to generate this parameter automatically?

**Comment by jettcc** [comment]
i made an attempt, i added a `def.bzl` file in the root directory:
```
load("@io_bazel_rules_go//go:def.bzl", _go_binary = "go_binary")

def go_binary(name, embed=[], **kwargs):
    binary_name = kwargs.get("out") or name
    _go_binary(
        name = name, 
        out = binary_name,
        embed = embed,
        **kwargs
    )
```
although he cannot change the `build.bazel` generated by `gazelle`
but it did output the binary file to the directory I expected after I executed `bazelisk build`.

so, is this a solution? but i think this implicit change will cause some confusion, and perhaps others may feel puzzled when reading the project.

**Comment by fmeum** [comment]
You can use `# gazelle:map_kind from_kind to_kind to_kind_load` to "redirect" `go_binary` to your custom macro which gives you both maximum flexibility and no unexpected behavior since you can use a different name.

**Comment by jettcc** [comment]
> You can use # gazelle:map_kind from_kind to_kind to_kind_load to "redirect" go_binary to your custom macro which gives you both maximum flexibility and no unexpected behavior since you can use a different name.

yes, i tried to do it this way, and it can solve my problem, but i think it's still necessary to provide an explicitly specified plan; perhaps this could be a long-term plan? thank you very much for your reply, i'll close this issue now.
